### ISSUE TITLE
fastANI2 based on MashMap3

### ISSUE THREAD

**Issue by jianshu93** [bkille/mashmap3-evaluation#1]
Dear Bryce, 

This is Jianshu, Kostas lab at Georgia Tech (the fastANI team), I noticed that MashMap3 is better in terms of estimation ANI below 85% than fastANI and skani, skani is very bad actually below 85%, see the discussion here: https://github.com/bluenote-1577/skani/issues/13

Since fastANI is the modification of MashMap2, I imagine MashMap could also be adjusted to have a new fastANI and compare with other ANI implementations. skani claims to be 20X faster than fastANI while lose accuracy at bowl 85% ANI, which is often very useful ANI range, other Minhash like Mash or Dashing can be accurate at around 80% ANI, consistent with fastANI. I am not a C++ person but more on the Rust side for sketching and nearest neighbor search related tasks for genomes.

Is there a plan or something for fastANI2 or something. I would be happy to test, contribute and benchmarking. I imagine it can be both fast but also accurate than fastANI first version. More accurate than skani.

Thanks,

Jianshu

**Comment by bkille** [comment]
Hi Jianshu!

Yes, the new version of MashMap could also be used to improve FastANI. I've taken a look at the FastANI code, and it shouldn't be *too* difficult to update it, but I likely won't be able to get around to doing it until later in the summer. I'll keep you posted!

-Bryce
